#!/bin/bash
set -e

# Install System Dependencies and s6-overlay
# This script installs all system dependencies needed for:
# - Posit R binaries
# - R package compilation
# - RStudio Server
# - s6-overlay init system

echo "=========================================="
echo "Installing System Dependencies"
echo "=========================================="

# Update package list
apt-get update

# First, install wget and curl which are needed for downloading s6-overlay later
echo "Installing basic download tools..."
apt-get install -y --no-install-recommends wget curl ca-certificates

# Install all other dependencies
# Includes:
#   - gnupg2, sudo: Basic utilities
#   - libopenblas, libpango, libtcl, libtk, etc.: Dependencies for Posit R binaries
#   - build-essential, gfortran: Build tools for R package compilation
#   - lib*-dev packages: R development dependencies
#   - libclang-dev, lsb-release: RStudio Server dependencies
#   - python3, python3-venv, python3-pip: Python and CloudOS CLI dependencies
#   - git, nano, vim: Development tools
#   - xz-utils, psmisc: System utilities
echo "Installing system dependencies..."
apt-get install -y --fix-missing \
    biber \
    binutils-common \
    build-essential \
    byacc \
    chromium \
    cmake \
    cmake-data \
    coinor-libcgl1 \
    coinor-libclp-dev \
    coinor-libclp1 \
    coinor-libcoinutils-dev \
    coinor-libcoinutils3v5 \
    coinor-libosi-dev \
    coinor-libosi1v5 \
    coinor-libsymphony-dev \
    coinor-libsymphony3 \
    comerr-dev \
    dbus \
    dbus-bin \
    dbus-daemon \
    dbus-session-bus-common \
    dbus-system-bus-common \
    dbus-user-session \
    dconf-gsettings-backend \
    dconf-service \
    devscripts \
    f2c \
    file \
    fort77 \
    gdal-data \
    gdal-plugins \
    gdb \
    gdebi \
    gfortran \
    ggobi \
    git \
    gnupg2 \
    gobject-introspection \
    gobject-introspection-bin \
    graphviz \
    gsfonts \
    gsfonts \
    gzip \
    hdf5-helpers \
    imagemagick \
    imagemagick-6-common \
    imagemagick-6.q16 \
    jags \
    less \
    libaec-dev \
    libaec0 \
    libalgorithm-c3-perl \
    libamd-comgr2 \
    libamd3 \
    libamdhip64-5 \
    libann0 \
    libaom-dev \
    libaom3 \
    libarchive-dev \
    libarchive-extract-perl \
    libarchive13t64 \
    libargon2-1 \
    libarmadillo-dev \
    libarmadillo12 \
    libarpack2-dev \
    libarpack2t64 \
    libasound2-data \
    libasound2t64 \
    libass9 \
    libatspi2.0-0t64 \
    libattr1 \
    libattr1-dev \
    libaudit-common \
    libaudit1 \
    libautovivification-perl \
    libavcodec-dev \
    libavcodec60 \
    libavfilter-dev \
    libavfilter9 \
    libavformat-dev \
    libavformat60 \
    libavutil-dev \
    libavutil58 \
    libb-hooks-endofscope-perl \
    libb-hooks-op-check-perl \
    libbabeltrace1 \
    libbinutils \
    libblas-dev \
    libblosc-dev \
    libblosc1 \
    libboost-all-dev \
    libbs2b0 \
    libbsd-dev \
    libbsd0 \
    libbtf2 \
    libbtparse2 \
    libbusiness-isbn-data-perl \
    libbusiness-isbn-perl \
    libbusiness-ismn-perl \
    libbusiness-issn-perl \
    libbz2-dev \
    libbz2-ocaml \
    libcairo2-dev \
    libcairomm-1.0-1v5 \
    libcairomm-1.0-dev \
    libcamd3 \
    libcbor0.10 \
    libccolamd3 \
    libcdt5 \
    libcfitsio-dev \
    libcfitsio10t64 \
    libcgi-pm-perl \
    libcgraph6 \
    libcholmod5 \
    libchromaprint1 \
    libcjson1 \
    libclang-dev \
    libclass-accessor-perl \
    libclass-c3-perl \
    libclass-data-inheritable-perl \
    libclass-inspector-perl \
    libclass-method-modifiers-perl \
    libclass-singleton-perl \
    libclone-perl \
    libcodec2-1.2 \
    libcolamd3 \
    libcolord2 \
    libcurl4-openssl-dev \
    libcxsparse4 \
    libdata-compare-perl \
    libdata-dump-perl \
    libdata-optlist-perl \
    libdata-uniqid-perl \
    libdate-simple-perl \
    libdatetime-calendar-julian-perl \
    libdatetime-format-builder-perl \
    libdatetime-format-strptime-perl \
    libdatetime-locale-perl \
    libdatetime-perl \
    libdatetime-timezone-perl \
    libdatrie-dev \
    libdav1d-dev \
    libdav1d7 \
    libdbd-mysql-perl \
    libdbi-perl \
    libdbus-1-3 \
    libdconf1 \
    libde265-0 \
    libde265-dev \
    libdebuginfod-common \
    libdebuginfod1t64 \
    libdevel-callchecker-perl \
    libdevel-stacktrace-perl \
    libdevmapper1.02.1 \
    libdjvulibre-dev \
    libdjvulibre-text \
    libdjvulibre21 \
    libdpkg-perl \
    libdw1t64 \
    libdynaloader-functions-perl \
    libegl-dev \
    libegl-mesa0 \
    libegl1 \
    libeigen3-dev \
    libelf1t64 \
    libencode-eucjpascii-perl \
    libencode-eucjpms-perl \
    libencode-hanextra-perl \
    libencode-jis2k-perl \
    libencode-locale-perl \
    libencode-perl \
    libepoxy0 \
    libeval-closure-perl \
    libevent-2.1-7t64 \
    libevent-core-2.1-7t64 \
    libevent-dev \
    libevent-extra-2.1-7t64 \
    libevent-openssl-2.1-7t64 \
    libevent-pthreads-2.1-7t64 \
    libexception-class-perl \
    libexif-dev \
    libexif12 \
    libexporter-tiny-perl \
    libext2fs-dev \
    libf2c2 \
    libf2c2-dev \
    libfabric1 \
    libfftw3-bin \
    libfftw3-dev \
    libfftw3-double3 \
    libfftw3-long3 \
    libfftw3-quad3 \
    libfftw3-single3 \
    libfido2-1 \
    libfile-copy-recursive-perl \
    libfile-find-rule-perl \
    libfile-listing-perl \
    libfile-sharedir-perl \
    libfile-slurper-perl \
    libflac12t64 \
    libflite1 \
    libfontconfig1-dev \
    libfontenc1 \
    libfreetype6-dev \
    libfreexl-dev \
    libfreexl1 \
    libfribidi-dev \
    libfuse-dev \
    libfuse2t64 \
    libfyba-dev \
    libfyba0t64 \
    libgbm1 \
    libgd3 \
    libgdal-dev \
    libgdal34t64 \
    libgdk-pixbuf-2.0-0 \
    libgdk-pixbuf-2.0-dev \
    libgdk-pixbuf2.0-bin \
    libgdk-pixbuf2.0-common \
    libgeos-c1t64 \
    libgeos-dev \
    libgeos3.12.1t64 \
    libgeotiff-dev \
    libgeotiff5 \
    libgif-dev \
    libgif7 \
    libgirepository-1.0-1 \
    libgirepository-1.0-dev \
    libgirepository-2.0-0 \
    libgirepository1.0-dev \
    libgit2-1.7 \
    libgit2-dev \
    libgl-dev \
    libgl1 \
    libgl1-mesa-dev \
    libgl1-mesa-dri \
    libglapi-mesa \
    libgles-dev \
    libgles1 \
    libgles2 \
    libglib2.0-0t64 \
    libglib2.0-bin \
    libglib2.0-data \
    libglib2.0-dev \
    libglib2.0-dev-bin \
    libglibmm-2.4-1t64 \
    libglibmm-2.4-dev \
    libglpk-dev \
    libglpk40 \
    libglu1-mesa \
    libglu1-mesa-dev \
    libglut3.12 \
    libglvnd-core-dev \
    libglvnd-dev \
    libglvnd0 \
    libglx-dev \
    libglx-mesa0 \
    libglx0 \
    libgme0 \
    libgmp-dev \
    libgmp10 \
    libgmp3-dev \
    libgmpxx4ldbl \
    libgnutls30t64 \
    libgprofng0 \
    libgsl-dev \
    libgsl27 \
    libgslcblas0 \
    libgsm1 \
    libgtk-3-0t64 \
    libgtk-3-common \
    libgtk2.0-0t64 \
    libgtk2.0-common \
    libgtk2.0-dev \
    libgtkmm-2.4-1t64 \
    libgtkmm-2.4-dev \
    libgts-0.7-5t64 \
    libgvc6 \
    libgvpr2 \
    libharfbuzz-dev \
    libhdf4-0-alt \
    libhdf4-alt-dev \
    libhdf5-103-1t64 \
    libhdf5-cpp-103-1t64 \
    libhdf5-dev \
    libhdf5-fortran-102t64 \
    libhdf5-hl-100t64 \
    libhdf5-hl-cpp-100t64 \
    libhdf5-hl-fortran-100t64 \
    libheif-dev \
    libheif-plugin-aomdec \
    libheif-plugin-libde265 \
    libheif1 \
    libhiredis-dev \
    libhiredis1.1.0 \
    libhsa-runtime64-1 \
    libhsakmt1 \
    libhtml-parser-perl \
    libhtml-tagset-perl \
    libhtml-tree-perl \
    libhtscodecs2 \
    libhttp-cookies-perl \
    libhttp-date-perl \
    libhttp-message-perl \
    libhttp-negotiate-perl \
    libhttp-parser-dev \
    libhttp-parser2.9 \
    libhwloc-dev \
    libhwloc-plugins \
    libhwloc15 \
    libhwy1t64 \
    libibverbs-dev \
    libibverbs1 \
    libicu-dev \
    libimath-3-1-29t64 \
    libimath-dev \
    libinchi1 \
    libio-html-perl \
    libio-socket-ssl-perl \
    libipc-run3-perl \
    libipt2 \
    libisl23 \
    libjpeg-dev \
    libjpeg-turbo-progs \
    libjs-jquery \
    libjs-jquery-ui \
    libjs-sphinxdoc \
    libjs-underscore \
    libjson-c-dev \
    libjson-c5 \
    libjsoncpp25 \
    libjxl0.7 \
    libkmlbase1t64 \
    libkmlconvenience1t64 \
    libkmldom1t64 \
    libkmlengine1t64 \
    libkmlregionator1t64 \
    libkmlxsd1t64 \
    libkmod2 \
    liblab-gamut1 \
    liblapack-dev \
    liblcms2-2 \
    liblcms2-dev \
    libldap2 \
    libldl3 \
    liblilv-0-0 \
    liblingua-translit-perl \
    liblist-allutils-perl \
    liblist-moreutils-perl \
    liblist-moreutils-xs-perl \
    liblist-someutils-perl \
    liblist-utilsby-perl \
    libllvm17t64 \
    liblog-log4perl-perl \
    liblqr-1-0 \
    liblqr-1-0-dev \
    libltdl-dev \
    libltdl7 \
    liblwp-mediatypes-perl \
    liblwp-protocol-https-perl \
    liblz4-dev \
    liblzma-dev \
    liblzma-dev \
    liblzma5 \
    libmaeparser1 \
    libmagick++-6-headers \
    libmagick++-6.q16-9t64 \
    libmagick++-6.q16-dev \
    libmagick++-dev \
    libmagick++-dev \
    libmagickcore-6-arch-config \
    libmagickcore-6-headers \
    libmagickcore-6.q16-7-extra \
    libmagickcore-6.q16-7t64 \
    libmagickcore-6.q16-dev \
    libmagickwand-6-headers \
    libmagickwand-6.q16-7t64 \
    libmagickwand-6.q16-dev \
    libmbedcrypto7t64 \
    libmd-dev \
    libmd0 \
    libmhash2 \
    libmime-charset-perl \
    libminizip-dev \
    libminizip1t64 \
    libmodule-build-perl \
    libmodule-implementation-perl \
    libmodule-runtime-perl \
    libmount-dev \
    libmount1 \
    libmp3lame0 \
    libmpc3 \
    libmpfr-dev \
    libmpfr6 \
    libmpg123-0t64 \
    libmro-compat-perl \
    libmunge2 \
    libmysofa1 \
    libmysqlclient-dev \
    libmysqlclient21 \
    libnamespace-autoclean-perl \
    libnamespace-clean-perl \
    libnet-http-perl \
    libnet-ssleay-perl \
    libnetcdf-dev \
    libnetcdf19t64 \
    libnghttp2-14 \
    libnl-3-200 \
    libnl-3-dev \
    libnl-route-3-200 \
    libnl-route-3-dev \
    libnode-dev \
    libnode-dev \
    libnode109 \
    libnorm-dev \
    libnorm1t64 \
    libnspr4 \
    libnss3 \
    libnuma-dev \
    libnuma1 \
    libnumber-compare-perl \
    libobjc-13-dev \
    libodbc2 \
    libodbccr2 \
    libodbcinst2 \
    libogdi-dev \
    libogdi4.1 \
    libogg0 \
    libopenbabel-dev \
    libopenbabel7 \
    libopenblas-dev \
    libopenexr-3-1-30 \
    libopenexr-dev \
    libopengl-dev \
    libopengl0 \
    libopenjp2-7 \
    libopenjp2-7-dev \
    libopenmpi-dev \
    libopenmpi3t64 \
    libopenmpt0t64 \
    libopus0 \
    libpackage-stash-perl \
    libpango-1.0-0 \
    libpango1.0-dev \
    libpangocairo-1.0-0 \
    libpangomm-1.4-1v5 \
    libpangomm-1.4-dev \
    libpangoxft-1.0-0 \
    libpaper-utils \
    libparams-classify-perl \
    libparams-util-perl \
    libparams-validate-perl \
    libparams-validationcompiler-perl \
    libparse-recdescent-perl \
    libparse-recdescent-perl \
    libparu0 \
    libpathplan4 \
    libpcre2-16-0 \
    libpcre2-32-0 \
    libpcre2-8-0 \
    libpcre2-dev \
    libpcre2-ocaml \
    libpcre2-posix3 \
    libpcsclite1 \
    libperl-dev \
    libperl5.38t64 \
    libpgm-5.3-0t64 \
    libpgm-dev \
    libplacebo338 \
    libpmix-dev \
    libpmix2t64 \
    libpng-dev \
    libpng16-16t64 \
    libpocketsphinx3 \
    libpoppler-cpp-dev \
    libpoppler-cpp0t64 \
    libpoppler-dev \
    libpoppler-glib-dev \
    libpoppler-glib8t64 \
    libpoppler-private-dev \
    libpoppler134 \
    libpostproc-dev \
    libpostproc57 \
    libpq-dev \
    libpq5 \
    libproj-dev \
    libproj25 \
    libprotobuf-dev \
    libprotobuf-lite32t64 \
    libprotobuf32t64 \
    libprotoc-dev \
    libprotoc32t64 \
    libpsm-infinipath1 \
    libpsm2-2 \
    libpython3.12-dev \
    libpython3.12-minimal \
    libpython3.12-stdlib \
    libpython3.12t64 \
    libqhull-dev \
    libqhull-r8.0 \
    libqhull8.0 \
    libqhullcpp8.0 \
    librabbitmq4 \
    libraptor2-0 \
    libraptor2-dev \
    librasqal3-dev \
    librasqal3t64 \
    librav1e0 \
    libraw23t64 \
    librbio4 \
    librdf0-dev \
    librdf0t64 \
    librdmacm1t64 \
    libreadline-dev \
    libreadonly-perl \
    libregexp-common-perl \
    librhash0 \
    librist4 \
    librole-tiny-perl \
    librsvg2-2 \
    librsvg2-common \
    librsvg2-dev \
    librttopo-dev \
    librttopo1 \
    librubberband2 \
    libsamplerate0 \
    libsasl2-dev \
    libsbml5-dev \
    libsbml5t64 \
    libserd-0-0 \
    libshine3 \
    libsigc++-2.0-0v5 \
    libsigc++-2.0-dev \
    libsnappy1v5 \
    libsndfile1 \
    libsodium-dev \
    libsombok3 \
    libsord-0-0 \
    libsort-key-perl \
    libsource-highlight-common \
    libsource-highlight4t64 \
    libsoxr0 \
    libspatialite-dev \
    libspatialite8t64 \
    libspecio-perl \
    libspeex1 \
    libspex2 \
    libsphinxbase3t64 \
    libspqr4 \
    libsqlite3-0 \
    libsqlite3-dev \
    libsratom-0-0 \
    libsrt1.5-gnutls \
    libssh-gcrypt-4 \
    libssh2-1-dev \
    libssh2-1t64 \
    libssh2-1t64 \
    libssl-dev \
    libssl3t64 \
    libstdc++-13-dev \
    libstdlib-ocaml \
    libsub-exporter-perl \
    libsub-exporter-progressive-perl \
    libsub-identify-perl \
    libsub-install-perl \
    libsub-name-perl \
    libsub-quote-perl \
    libsuitesparse-dev \
    libsuitesparse-mongoose3 \
    libsuitesparseconfig7 \
    libsuperlu-dev \
    libsuperlu6 \
    libsvtav1enc1d1 \
    libswresample-dev \
    libswresample4 \
    libswscale-dev \
    libswscale7 \
    libsystemd-shared \
    libsystemd0 \
    libsz2 \
    libtcl8.6 \
    libtext-bibtex-perl \
    libtext-csv-perl \
    libtext-csv-xs-perl \
    libtext-glob-perl \
    libtext-roman-perl \
    libthai-dev \
    libtheora0 \
    libtie-cycle-perl \
    libtiff-dev \
    libtiff-opengl \
    libtiff-tools \
    libtiff5-dev \
    libtiff5-dev \
    libtiff6 \
    libtiffxx6 \
    libtimedate-perl \
    libtirpc-dev \
    libtk8.6 \
    libtry-tiny-perl \
    libturbojpeg \
    libtwolame0 \
    libucx0 \
    libudfread0 \
    libudfread0 \
    libudunits2-0 \
    libudunits2-data \
    libudunits2-dev \
    libumfpack6 \
    libunibreak5 \
    libunicode-linebreak-perl \
    libunistring5 \
    liburi-perl \
    liburiparser-dev \
    liburiparser1 \
    libuuid1 \
    libuv1-dev \
    libuv1t64 \
    libva-drm2 \
    libva-x11-2 \
    libva2 \
    libvariable-magic-perl \
    libvdpau1 \
    libvidstab1.1 \
    libvorbis0a \
    libvorbisenc2 \
    libvorbisfile3 \
    libvpl2 \
    libvpx9 \
    libvulkan1 \
    libwmf-0.2-7 \
    libwmf-dev \
    libwmflite-0.2-7 \
    libwww-perl \
    libwww-robotrules-perl \
    libx11-xcb1 \
    libx264-164 \
    libx265-199 \
    libx265-dev \
    libxaw7 \
    libxcb-dri2-0 \
    libxcb-dri3-0 \
    libxcb-glx0 \
    libxcb-present0 \
    libxcb-randr0 \
    libxcb-sync1 \
    libxcb-xfixes0 \
    libxcomposite-dev \
    libxcomposite1 \
    libxcursor-dev \
    libxcursor1 \
    libxdamage-dev \
    libxdamage1 \
    libxerces-c-dev \
    libxerces-c3.2t64 \
    libxfixes-dev \
    libxfixes3 \
    libxft-dev \
    libxi-dev \
    libxi6 \
    libxinerama-dev \
    libxinerama1 \
    libxkbcommon0 \
    libxml-libxml-perl \
    libxml-libxml-simple-perl \
    libxml-libxslt-perl \
    libxml-namespacesupport-perl \
    libxml-sax-base-perl \
    libxml-sax-perl \
    libxml-simple-perl \
    libxml-writer-perl \
    libxml2 \
    libxml2-dev \
    libxml2-utils \
    libxmu6 \
    libxnvctrl0 \
    libxpm-dev \
    libxpm4 \
    libxrandr-dev \
    libxrandr2 \
    libxshmfence1 \
    libxslt1-dev \
    libxslt1.1 \
    libxss-dev \
    libxstring-perl \
    libxt-dev \
    libxtst6 \
    libxvidcore4 \
    libxxf86vm1 \
    libyajl-dev \
    libyajl2 \
    libzimg2 \
    libzix-0-0 \
    libzmq3-dev \
    libzmq5 \
    libzvbi-common \
    libzvbi0t64 \
    locales \
    lsb-release \
    m4 \
    mono-4.0-gac \
    mono-gac \
    mono-runtime-common \
    mono-runtime-sgen \
    mono-runtime \
    mount \
    mpi-default-bin \
    mysql-common \
    nano \
    nettle-dev \
    node-acorn \
    node-busboy \
    node-cjs-module-lexer \
    node-undici \
    node-xtend \
    nodejs \
    ocaml-base \
    ocl-icd-libopencl1 \
    ocl-icd-opencl-dev \
    opencl-c-headers \
    opencl-clhpp-headers \
    openjdk-21-jdk \
    openjdk-21-jdk-headless \
    openjdk-21-jre \
    openjdk-21-jre-headless \
    openmpi-bin \
    openmpi-common \
    openssh-client \
    openssl \
    pandoc \
    pango1.0-tools \
    perl-openssl-defaults \
    pkg-config \
    proj-data \
    protobuf-compiler \
    psmisc \
    pwgen \
    python3 \
    python3-chardet \
    python3-numpy \
    python3-pip \
    python3-pkgconfig \
    python3-venv \
    sqlite3 \
    sudo \
    tabix \
    tcl \
    tex-common \
    tk \
    tk-dev \
    tzdata \
    ucf \
    unzip \
    vim \
    xz-utils \
    zip \
    zlib1g-dev \
    zstd

# Clean up apt cache
rm -rf /var/lib/apt/lists/*

echo "System dependencies installed successfully"

# ==========================================
# Locale Configuration
# ==========================================
echo "Configuring locales..."
echo "en_US.UTF-8 UTF-8" >> /etc/locale.gen
locale-gen en_US.utf8
/usr/sbin/update-locale LANG=en_US.UTF-8

echo "Locales configured"

# ==========================================
# Install s6-overlay for Process Supervision
# ==========================================
echo "=========================================="
echo "Installing s6-overlay"
echo "=========================================="

# Using v2.2.0.3 (last stable v2 release) for native /etc/cont-init.d/ support
S6_VERSION=${S6_VERSION:-v2.2.0.3}
echo "s6-overlay version: ${S6_VERSION}"

cd /tmp

# Download s6-overlay v2
echo "Downloading s6-overlay..."
wget -q "https://github.com/just-containers/s6-overlay/releases/download/${S6_VERSION}/s6-overlay-amd64.tar.gz"

# Extract s6-overlay
# Use proper tar options to avoid overwriting existing files
echo "Extracting s6-overlay..."
tar -xzf s6-overlay-amd64.tar.gz -C / --exclude='./bin' --exclude='./sbin'
tar -xzf s6-overlay-amd64.tar.gz -C /usr ./bin ./sbin 2>/dev/null || true

# Clean up
rm s6-overlay-amd64.tar.gz

echo "s6-overlay installed successfully"
echo "=========================================="
